"""Deterministic file classification. No LLM.

Every heuristic here is biased toward `UNKNOWN`. Misreading a real source file
as a test or a vendored dependency is a misclassification with no model in the
loop to catch it, so a rule fires only on evidence, never on a hunch.

The classification is *information*, not a verdict. What is done with it is the
policy question in `sift.prefilter`, and the answer is deliberately conservative.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from posixpath import basename

from sift.models.context import FileClass
from sift.paths import UnsafePathError, normalize_uri, read_text_head, resolve

#: Directory names that mean "not our code" across ecosystems. Matched as whole
#: path segments, never as substrings — `src/nodes/` must not match `node_modules`.
VENDOR_DIRS = frozenset(
    {
        "node_modules",
        "vendor",
        "vendored",
        "third_party",
        "thirdparty",
        "external",
        "site-packages",
        "dist-packages",
        "bower_components",
        "jspm_packages",
        "packs",
        ".venv",
        "venv",
        "virtualenv",
        "eggs",
        ".eggs",
        "gems",
        "godeps",
        "_vendor",
    }
)

#: Whole path segments that mean a test tree.
TEST_DIRS = frozenset(
    {"test", "tests", "testing", "spec", "specs", "__tests__", "e2e", "integration_tests"}
)

#: Whole path segments that mean fixture or sample data.
#:
#: `examples`, `sample`, and `samples` are deliberately absent. Example code is
#: code users copy into their own projects, so a vulnerability there propagates
#: outward rather than staying inert. Measured on the corpus, treating
#: `examples/` as a fixture would have labelled 64 of 103 real findings as
#: dismissible, which is exactly the overreach this classifier must not make.
FIXTURE_DIRS = frozenset(
    {
        "fixtures",
        "fixture",
        "testdata",
        "test_data",
        "__fixtures__",
        "golden",
        "snapshots",
        "__snapshots__",
        "mocks",
        "__mocks__",
    }
)

#: Whole path segments holding build or generation output.
#:
#: Only unambiguous ones. `gen`, `out`, and `obj` are three-letter names that
#: mean something else in plenty of repos, and `migrations` are routinely
#: hand-edited and run against a production database — none of those is evidence
#: of machine-written code.
GENERATED_DIRS = frozenset(
    {
        "generated",
        "__generated__",
        "_generated",
        "build",
        "dist",
        "target",
        ".next",
    }
)

TEST_FILE_RE = re.compile(
    r"""^(
        test_.+            |   # Python: test_foo.py
        .+_test            |   # Go, Python: foo_test.go
        .+\.test           |   # JS: foo.test.js
        .+\.spec           |   # JS: foo.spec.ts
        .+Test             |   # Java: FooTest.java
        .+Tests            |
        .+TestCase         |
        conftest               # pytest fixtures live here
    )$""",
    re.VERBOSE,
)

#: Suffixes that only appear on machine-written files.
GENERATED_SUFFIXES = (
    ".pb.go",
    ".pb.py",
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".g.cs",
    ".generated.ts",
    ".generated.js",
    ".designer.cs",
    "_generated.go",
    ".min.js",
    ".min.css",
    ".bundle.js",
)

#: Markers a generator writes into the file itself. The conventional Go form is
#: matched exactly per its spec; the rest are matched case-insensitively.
GENERATED_MARKERS = (
    "code generated by",
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by the protocol buffer compiler",
    "this file was generated",
)


@dataclass(frozen=True)
class Classification:
    """What the classifier concluded, and what convinced it."""

    file_class: FileClass
    #: Human-readable evidence. Empty for UNKNOWN and SOURCE.
    reason: str = ""
    #: True when a file's contents were read to decide. Path-only decisions are
    #: cheaper but weaker, and the distinction matters when auditing a mistake.
    used_content: bool = False


def _segments(uri: str) -> list[str]:
    return [s for s in normalize_uri(uri).split("/") if s not in ("", ".")]


def _stem(name: str) -> str:
    """Filename without any extension. `foo.test.ts` -> `foo.test`, then `foo`."""
    return name.split(".", 1)[0] if name.startswith(".") else Path(name).stem


def classify(uri: str, repo_root: Path | None = None) -> Classification:
    """Classify one artifact URI.

    ``repo_root`` enables the content check for generated-code markers, which is
    the only signal that cannot be read off a path. Without it the classifier is
    path-only and says so through ``used_content``.

    Order matters. Vendored wins over test, because `node_modules/x/test/y.js` is
    somebody else's test, and the vendored fact is the more useful one.
    """
    segments = _segments(uri)
    if not segments:
        return Classification(FileClass.UNKNOWN, "empty path")

    name = basename(normalize_uri(uri))
    lowered = [s.lower() for s in segments[:-1]]

    if hit := next((s for s in lowered if s in VENDOR_DIRS), None):
        return Classification(FileClass.VENDORED, f"path segment {hit!r}")

    if hit := next((s for s in lowered if s in FIXTURE_DIRS), None):
        return Classification(FileClass.FIXTURE, f"path segment {hit!r}")

    if hit := next((s for s in lowered if s in GENERATED_DIRS), None):
        return Classification(FileClass.GENERATED, f"path segment {hit!r}")

    if hit := next((s for s in lowered if s in TEST_DIRS), None):
        return Classification(FileClass.TEST, f"path segment {hit!r}")

    lower_name = name.lower()
    if hit := next((s for s in GENERATED_SUFFIXES if lower_name.endswith(s)), None):
        return Classification(FileClass.GENERATED, f"filename suffix {hit!r}")

    if TEST_FILE_RE.match(_stem(name)):
        return Classification(FileClass.TEST, f"filename {name!r}")

    if repo_root is not None:
        try:
            head = read_text_head(resolve(repo_root, uri))
        except UnsafePathError:
            return Classification(FileClass.UNKNOWN, "path refused as unsafe")
        if head:
            haystack = head.lower()
            if hit := next((m for m in GENERATED_MARKERS if m in haystack), None):
                return Classification(FileClass.GENERATED, f"marker {hit!r}", used_content=True)
            return Classification(FileClass.SOURCE, "", used_content=True)
        # File unreadable or missing. Path said nothing either, so we know nothing.
        return Classification(FileClass.UNKNOWN, "file not readable from the repo root")

    # Path-only, and no rule fired. Not the same as knowing it is source.
    return Classification(FileClass.UNKNOWN, "no path rule matched, contents not read")
